name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.202
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test Tests/YY.YellowPlatformFormats.Core.Tests/YY.YellowPlatformFormats.Core.Tests.csproj
    - name: Deploy
      run: chmod +x ./Scripts/deploy.sh && ./Scripts/deploy.sh ${{secrets.NUGET_API_KEY}}
